<?php

/**
 * Quest Lab Requisition PDF Download Handler
 *
 * This file contains the DownloadRequisition class which is responsible for
 * delivering requisition form PDFs to the user's browser. When a lab order
 * is transmitted, this class facilitates the delivery of the associated PDF
 * requisition document to the user.
 *
 * @package   OpenEMR
 * @link      http://www.open-emr.org
 * @author    Sherwin Gaddis <sherwingaddis@gmail.com>
 * @copyright Copyright (c) Sherwin Gaddis <sherwingaddis@gmail.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

namespace Juggernaut\Quest\Module;

/**
 * Class DownloadRequisition
 *
 * Handles the delivery of requisition form PDFs to the user's browser.
 * This class sets the appropriate HTTP headers for PDF delivery and
 * streams the file content to the browser, enabling users to view and
 * print laboratory requisition forms generated by Quest Diagnostics.
 *
 * @package Juggernaut\Quest\Module
 */
class DownloadRequisition
{
    /**
     * Path to the directory containing requisition form PDFs
     * @var string
     */
    private string $pdf;

    /**
     * Constructor - Initialize with PDF directory path
     *
     * Sets up the path to the directory where requisition form PDFs
     * are stored based on the site's document configuration.
     */
    public function __construct()
    {
        $this->pdf = Bootstrap::requisitionFormPath();
    }
    
    /**
     * Downloads a lab requisition PDF to the user's browser
     *
     * Sets the appropriate HTTP headers to deliver a PDF file
     * as an inline document in the browser. Performs validation
     * to ensure the file exists and is not empty before sending.
     * 
     * @param string $name The filename of the requisition PDF to download
     * @return void
     */
    public function downloadLabPdfRequisition($name): void
    {
        if (filesize($this->pdf . $name) == 0) {
            error_log('Lab requisition form empty file');
            return;
        }
        error_log('Downloading lab pdf ' . $name);
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename=LabRequisition.pdf');
        header('Content-Transfer-Encoding: binary');
        header('Content-Length: ' . filesize($this->pdf . $name));
        header('Accept-Ranges: bytes');
        readfile($this->pdf . $name);
    }
}
